INSERT INTO product (name, description, url_image, quantity, price, date, active, user_id)
VALUES
  ('Apple iPhone SE', 'Fully functional, excellent cosmetic condition and set to factory defaults.  As these are pre-owned, these units may or may not have very minor and for the most part insignificant scratches from previous use.  Very beautiful units!  Unlocked.', 'https://i5.walmartimages.com/asr/5a1e26fa-612a-45c8-806d-20b1adb4dd4f_1.4be750614219271be62b565e0c76f873.jpeg?odnHeight=2000&odnWidth=2000&odnBg=FFFFFF', 1000, 155, '2022-11-15 09:39:49.866+13', true, 1),
  ('Apple iPhone 11', 'This product is in good cosmetic condition, there will be signs of wear which may include scratches, visible scuffs or screen discoloration but nothing that will impair functionality. Battery health will be a minimum of 80 percent. The item has been fully tested, restored to factory settings and is in excellent working order.', 'https://i.ebayimg.com/images/g/dJEAAOSwJfthDS3V/s-l1600.jpg', 1000, 830, '2022-11-15 09:39:49.866+13', true, 1),
  ('Fender Stratocaster', 'A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is applicable). Packaging should be the same as what is found in a retail store, unless the item is handmade or was packaged by the manufacturer in non-retail packaging, such as an unprinted box or plastic bag.', 'https://i.ebayimg.com/images/g/0RIAAOSwyM1hXMh~/s-l1600.jpg', 1000, 744, '2022-11-15 09:39:49.866+13', true, 1),
  ('Table Set', 'The cozy, classic feel of a traditional village tavern inspired this 5-piece pub set. A design investment, it’s constructed with durable wood and features a rich brown finish for timeless versatility.', 'https://m.media-amazon.com/images/I/91oPfLoJjGL._AC_SL1500_.jpg', 1000, 150, '2022-11-15 09:39:49.866+13', true, 1),
  ('Samsung 32-Inch QLED', 'Enjoy ultra-intense 4K vivid color and sharpened clarity with the Q60A/Q60AB. It combines Quantum Dot Technology with the power of 100 percent Color Volume¹ to deliver a billion of shades for colorful, razor-sharp visuals. The ultra-smart Quantum Processor 4K Lite automatically upscales and transforms your content into 4K. Dual LED² backlighting adjusts and coordinates with content in real time to enhance contrast and detail. Plus, with the rechargeable SolarCellRemote, you can easily access and control Smart TV and all your connected devices. ¹QLED televisions can produce 100 percent Color Volume in the DCI-P3 color space, the format for most cinema screens and HDR movies for television. ²32" Dual LED not available.', 'https://m.media-amazon.com/images/I/71G6eW8H8hL._AC_SL1500_.jpg', 1000, 447, '2022-11-15 09:39:49.866+13', true, 1),
  ('6-Speed Mixer', 'Whip up an airy meringue or decadent cake with the Hamilton Beach hand mixer. This versatile mixer is your go-to appliance for mixing, whisking, and folding with 250W of peak power. A built-in bowl rest makes it easier to set the mixer down when adding ingredients. The mixer has six speeds, including quick burst functions for additional power at any speed. The Hamilton Beach hand mixer is not just about performance, it’s also designed for easy storage. A convenient snap-on case keeps attachments together, so you don"t have to search for them each time you need them. Includes traditional beaters and whisk.', 'https://media.istockphoto.com/id/532558882/photo/red-kitchen-mixer.jpg?s=612x612&w=0&k=20&c=AMZqDyoJMXXZ_F4zERvvWwyVAKaSZ_um4-2RRPZCN5c=', 1000, 100, '2022-11-15 09:39:49.866+13', true, 1),
  ('Car Seat', 'Safely ride rear-facing longer! The Graco Extend2Fit Convertible Car Seat grows with your child from rear-facing harness (4-50 lbs) to forward-facing harness (22-65 lbs). It features a 4-position extension panel that provides up to 5” of extra rear-facing legroom, allowing your child to safely ride rear-facing longer. Children are safer riding rear-facing and should ride rear-facing as long as possible, until they reach the maximum rear-facing height or weight rating for their car seat. With Extend2Fit, the adjustable extension panel and 50 lbs rear-facing weight limit allow the seat to grow with your child in rear-facing mode, providing extended rear-facing use. The seat features the No-Rethread Simply Safe Adjust Harness System, which allows you to adjust the height of the headrest and harness in one motion, and InRight LATCH for a one-second LATCH attachment. Harnessing is made easier with fuss-free harness storage pockets that conveniently hold the harness out of the way while you get baby in and out of the car seat. This car seat is Graco ProtectPlus Engineered to help protect in frontal, side, rear, and rollover crashes.', 'https://m.media-amazon.com/images/I/71wNWtNb0sL._SL1500_.jpg', 1000, 300, '2022-11-15 09:39:49.866+13', true, 1),
  ('Citizen BL5550', 'New item in original open box. Water-Resistant, Mineral Crystal, Luminous Hands, Date Indicator, Alarm, Perpetual Calendar, 12-Hour Dial, Chronograph', 'https://i.ebayimg.com/images/g/sH4AAOSwp1tjlXR3/s-l1600.jpg', 1000, 300, '2022-11-15 09:39:49.866+13', true, 1);
